image: ruby:2.3

pages:
  script:
  - gem install jekyll
  - gem install jekyll-paginate
  - gem install bourbon
  - gem install jemoji
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
