# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Jobs"
description: > # this means to ignore newlines until "email:"
   Job openings offered by CocoaHeadsNL sponsors

email: foundation@cocoaheads.nl
#blog logo
#logo: "/assets/images/CocoaHeadsNL.png"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'CocoaHeadsNL'
author: 'CocoaHeadsNL'
author_image: "/assets/images/CocoaHeadsNL.png"

paginate:	5

url: "http://jobs.cocoaheads.nl" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/cocoaheadsnl
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/cocoaheadsnl
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
